### ISSUE TITLE
Training on SMAC takes too much time

### ISSUE THREAD

**Issue by Lavezlyn** [PKU-MARL/HARL#68]
Hello! I am running experiments on the SMAC environment using HAPPO and MAPPO algorithms. I've checked previous issues and saw it generally takes **a few hours** to complete experiments on SMAC. However, I use a single H800 GPU to run the training using the command shown in `README`:

`python train.py --load_config HARL/tuned_configs/smac/3s5z/happo/config.json --exp_name happo-3s5z`

And it takes approximately **7h to complete 1520000/20000000 timesteps**.

I wonder if it is normal. How can I speed up the training process?

Note: I simultaneously run 6 SMAC experiments on a single H800 GPU, each starting with the message that shows the GPU is being used for training. The MEM is 12.7%, and the UTL is ~42% at its peak. My PyTorch version is 2.2.0, which is compatible with Python=3.8, CUDA=12.2, and NVIDIA H800 GPU (which has CUDA capability sm_90). My numpy version is above 1.9.0, which leads to deprecation errors, but I solve it by changing the codes from `np.bool` to `np.bool_`, `np.int` to `np.int32`.

**Comment by Lavezlyn** [comment]
This is because the `gym` version is `0.26.2`, leading to an extremely slow rollout procedure (representing low FPS and low CPU utilization rate).  I downgraded it to `0.21.0`, and the problem is solved. 

In `README.md`, there are no explicit instructions on guiding the user to install `gym` in the section on installing _SMAC_ environment. Only mention that you should resolve dependencies after all the environment installations by `pip install gym==0.21.0`. If users only want to install _SMAC_ environment and follow the instructions of the corresponding section, they may run into `No module...` error the first time they run SMAC experiments, hence the manual installation of faulty versions of gym.

**Comment by Ivan-Zhong** [comment]
Hi. Thank you for carefully identifying the issue and providing a solution. I have updated the README to clarify the installation steps. :)
